version: "3"

services:
  postgresus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4005:4005"

  postgresus-db:
    image: postgres:17
    # we use default values, but do not expose
    # PostgreSQL ports so it is safe
    environment:
      - POSTGRES_DB=postgresus
      - POSTGRES_USER=postgresus
      - POSTGRES_PASSWORD=postgresus
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: postgresus-db
    command: -p 5437
    shm_size: 10gb
