name: Validate CSS Build

on:
  pull_request:
    paths:
      - 'src/input.css'
      - 'index.html'
      - '*.html'
      - 'tailwind.config.js'
      - 'package.json'
  workflow_dispatch:

jobs:
  validate-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build-css

      - name: Check if CSS is up to date
        run: |
          if ! git diff --quiet styles.min.css; then
            echo "❌ styles.min.css is not up to date!"
            echo "Please run 'npm run build-css' locally and commit the changes."
            git diff styles.min.css
            exit 1
          else
            echo "✅ styles.min.css is up to date!"
          fi
